version: '3'

services:
  # Сервіс для Laravel (PHP)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    command: sh -c "chown -R www-data:www-data /var/www/html && php-fpm"
    networks:
      - laravel
    depends_on:
      - db

  # Сервіс для Nginx
  web:
    image: nginx:alpine
    container_name: laravel_web
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - laravel
    depends_on:
      - app

  # Сервіс для MariaDB
  db:
    image: mariadb:10.5
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

  # Сервіс для PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8080:80"
    networks:
      - laravel
    depends_on:
      - db

volumes:
  db_data:

networks:
  laravel:
